### ISSUE TITLE
Exceptions have occurred while Couchbase pods are down for Configuration&Organization services

### ISSUE THREAD

**Issue by PavloEsco** [scalecube/scalecube-configuration-service#117]
STR

**1.** Run the *chaos* bash script for Couchbase
`#!/bin/bash
while true
do
chaos run Pods-CouchBase-healthy.json
sleep 15
done`

**Json**

`{
  "version": "0.0.1",
  "title": "Terminate pods from couchbase app",
  "description": "We expect that the application should run fine even when pods are deleted",
  "tags": [
      "kubernetes",
      "couchbase",
      "chaos"
  ],
  "steady-state-hypothesis": {
      "title": "Services are all available and healthy",
      "probes": [
          {
              "type": "probe",
              "name": "couchbase-healthy",
              "tolerance": true,
              "provider": {
                  "type": "python",
                  "module": "chaosk8s.probes",
                  "func": "microservice_available_and_healthy",
                  "arguments": {
                      "name": "couchbaseha",
                      "ns": "couchbase",
                      "label_selector": ""
                  }
              }
          }
      ]
  },
  "method": [
      {
          "type": "action",
          "name": "terminate-pod",
          "provider": {
              "type": "python",
              "module": "chaosk8s.pod.actions",
              "func": "terminate_pods",
              "arguments": {
                  "label_selector": "location=different",
                  "rand": true,
                  "ns": "couchbase"
              }
          },
          "pauses": {
              "after": 25
          }
      }
  ],
  "rollbacks": []
}`

**2.** Wait up to 30 sec upon the script to be performed and start to execute some of the API calls for read or write operation for example:
*/organizations/getOrganization* and */configuration/save*

**3.** Wait up to 1 min upon the script to be performed again and continue to execute some of the API calls for read or write operation

**AR:**
**2.**
 `{"sig":2,"q":"/io.scalecube.services.error/500","sid":2,"d":{"errorCode":500,"errorMessage":"java.util.concurrent.TimeoutException: {\"b\":\"organizations\",\"s\":\"kv\",\"t\":2500000,\"i\":\"0x44be\"}"}}
{code}`

**3.**
`{"sig":2,"q":"/io.scalecube.services.error/500","sid":7,"d":{"errorCode":500,"errorMessage":"io.scalecube.configuration.repository.exception.TransientDataAccessResourceException"}}
io.scalecube.configuration.repository.exception.TransientDataAccessResourceException: null
	at io.scalecube.configuration.repository.couchbase.CouchbaseExceptionTranslator.translateRuntimeExceptionIfPossible(CouchbaseExceptionTranslator.java:112) ~[app.jar:?]
	at io.scalecube.configuration.repository.couchbase.CouchbaseExceptionTranslator.translateExceptionIfPossible(CouchbaseExceptionTranslator.java:58) ~[app.jar:?]
	at reactor.core.publisher.Mono.lambda$onErrorMap$24(Mono.java:2991) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.Operators.error(Operators.java:181) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3694) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at reactor.core.publisher.MonoNext$NextSubscriber.onError(MonoNext.java:87) [reactor-core-3.2.6.RELEASE.jar:3.2.6.RELEASE]
	at rx.internal.reactivestreams.PublisherAdapter$1.onError(PublisherAdapter.java:87) [rxjava-reactive-streams-1.2.1.jar:1.2.1]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) [rxjava-1.2.2.jar:1.2.2]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OperatorSerialize$1.onError(OperatorSerialize.java:52) [rxjava-1.2.2.jar:1.2.2]
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:152) [rxjava-1.2.2.jar:1.2.2]
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4$1.onError(OperatorOnErrorResumeNextViaFunction.java:122) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:44) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeThrow.call(OnSubscribeThrow.java:28) [rxjava-1.2.2.jar:1.2.2]
	at rx.Observable.unsafeSubscribe(Observable.java:10140) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:142) [rxjava-1.2.2.jar:1.2.2]
	at rx.observers.Subscribers$5.onError(Subscribers.java:230) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) [rxjava-1.2.2.jar:1.2.2]
	at rx.observers.Subscribers$5.onNext(Subscribers.java:235) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:159) [rxjava-1.2.2.jar:1.2.2]
	at rx.Subscriber.setProducer(Subscriber.java:205) [rxjava-1.2.2.jar:1.2.2]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102) [rxjava-1.2.2.jar:1.2.2]
	at rx.Subscriber.setProducer(Subscriber.java:205) [rxjava-1.2.2.jar:1.2.2]
	at rx.Subscriber.setProducer(Subscriber.java:205) [rxjava-1.2.2.jar:1.2.2]
	at rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:103) [rxjava-1.2.2.jar:1.2.2]
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:508) [java-client-2.7.3.jar:?]
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.access$000(AbstractGenericHandler.java:86) [java-client-2.7.3.jar:?]
	at com.couchbase.client.core.endpoint.AbstractGenericHandler$1.call(AbstractGenericHandler.java:526) [java-client-2.7.3.jar:?]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) [rxjava-1.2.2.jar:1.2.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.couchbase.client.java.error.TemporaryFailureException
	at com.couchbase.client.java.subdoc.SubdocHelper.commonSubdocErrors(SubdocHelper.java:68) ~[java-client-2.7.3.jar:?]
	at com.couchbase.client.java.subdoc.AsyncMutateInBuilder$4.call(AsyncMutateInBuilder.java:1405) ~[java-client-2.7.3.jar:?]
	at com.couchbase.client.java.subdoc.AsyncMutateInBuilder$4.call(AsyncMutateInBuilder.java:1392) ~[java-client-2.7.3.jar:?]
	at com.couchbase.client.java.subdoc.AsyncMutateInBuilder$15$1.call(AsyncMutateInBuilder.java:1635) ~[java-client-2.7.3.jar:?]
	at com.couchbase.client.java.subdoc.AsyncMutateInBuilder$15$1.call(AsyncMutateInBuilder.java:1625) ~[java-client-2.7.3.jar:?]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69) ~[rxjava-1.2.2.jar:1.2.2]
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.couchbase.client.core.message.kv.subdoc.simple.SimpleSubdocResponse.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109) ~[rxjava-1.2.2.jar:1.2.2]`

`ATTRIBUTES
{
contextMap {    
}
date    2019-05-07T12:43:00.709Z
endOfBatch  false
host    ip-10-200-27-76.eu-west-3.compute.internal
instant {   
epochSecond 1557232980
nanoOfSecond    709000000
}
level   ERROR
loggerFqcn  org.apache.logging.slf4j.Log4jLogger
loggerName  io.scalecube.configuration.ConfigurationServiceImpl
service configuration-service
thread  cb-computations-3
threadId    24
threadPriority  5
thrown {    
cause { 
cause { 
commonElementCount  22
extendedStackTrace  rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.couchbase.client.core.message.kv.subdoc.simple.SimpleSubdocResponse.class
    at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109) ~[rxjava-1.2.2.jar:1.2.2]
localizedMessage    OnError while emitting onNext value: com.couchbase.client.core.message.kv.subdoc.simple.SimpleSubdocResponse.class
message OnError while emitting onNext value: com.couchbase.client.core.message.kv.subdoc.simple.SimpleSubdocResponse.class
name    rx.exceptions.OnErrorThrowable$OnNextValue
}`

**ER:** User should be able to write and read without long delay ( up to 10 sec )

**Comment by PavloEsco** [comment]
Agreed to wrap the exceptions described above and  Return the relevant error message:
`There is a temporary problem with the service. Please try again in a few seconds.`

@stingion
